# see https://docs.gradle.org/current/userguide/platforms.html

[versions]
accompanist-themeadapter-material3 = "0.36.0"
android-fhir-common = "0.1.0-alpha05"
android-fhir-engine = "0.1.0-beta05"
android-fhir-knowledge = "0.1.0-beta01"
androidx-activity = "1.7.2"
androidx-activity-compose = "1.10.1"
androidx-appcompat = "1.6.1"
androidx-arch-core = "2.2.0"
androidx-benchmark = "1.4.0-rc01"
androidx-benchmark-macro = "1.4.0-rc01"
androidx-compose-bom = "2025.07.00"
androidx-constraintlayout = "2.1.4"
androidx-core = "1.10.1"
androidx-datastore = "1.0.0"
androidx-espresso = "3.5.1"
androidx-fragment = "1.6.0"
androidx-lifecycle = "2.8.7"
androidx-navigation = "2.6.0"
androidx-navigation-compose = "2.8.9"
androidx-profilerinstaller = "1.4.1"
androidx-recyclerview = "1.4.0"
androidx-room = "2.7.1"
androidx-sqlite = "2.5.0"
androidx-test-core = "1.6.1"
androidx-test-ext-junit = "1.1.5"
androidx-test-rules = "1.5.0"
androidx-test-runner = "1.5.0"
androidx-tracing = "1.3.0"
androidx-work = "2.8.1"
glide = "4.16.0"
junit = "4.13.2"
kotlin = "2.1.20"
kotlinx-coroutines = "1.8.1"
kotlinx-serialization-json = "1.8.1"
logback-android = "3.0.0"
material = "1.12.0"
opencds-cqf-fhir = "3.8.0"
truth = "1.1.5"
uiautomator = "2.3.0"
desugarJdkLibs = "2.0.3"
fhir-ucum = "1.0.3"
guava = "32.1.3-android"
hapi-fhir = "6.8.0"
hapi-fhir-core = "6.0.22"
robolectric = "4.10.3"
apache-commons-compress = "1.21"
http = "4.11.0"
jackson = "2.13.5"
jackson-core = "2.15.2"
json-tools-patch = "1.13"
json-assert = "1.5.1"
mlkit-barcode-scanning = "16.1.1"
mlkit-object-detection = "16.2.3"
mlkit-object-detection-custom = "16.3.1"
mockito-inline = "4.0.0"
mockito-kotlin = "3.2.0"
nimbus = "9.31"
play-services-location = "21.0.1"
retrofit = "2.9.0"
sqlcipher = "4.5.4"
timber = "5.0.1"
woodstox = "6.5.1"
xerces = "2.12.2"
xml-unit = "2.9.1"
zxing = "3.4.1"
jacoco = "0.8.10"
android-gradle-plugin = "8.9.2"
benchmark-plugin = "1.4.0-rc01"
fladle = "0.17.4"
ksp-plugin = "2.1.20-2.0.1"
navigation-safe-args = "2.6.0"
ruler = "1.2.1"
spotless = "4.17.0"
dokka = "1.9.20"

[libraries]
accompanist-themeadapter-material3 = { module = "com.google.accompanist:accompanist-themeadapter-material3", version.ref = "accompanist-themeadapter-material3"}
android-fhir-common = { module = "com.google.android.fhir:common", version.ref = "android-fhir-common" }
android-fhir-engine = { module = "com.google.android.fhir:engine", version.ref = "android-fhir-engine" }
android-fhir-knowledge = { module = "com.google.android.fhir:knowledge", version.ref = "android-fhir-knowledge" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-core" }
androidx-benchmark-junit4 = { module = "androidx.benchmark:benchmark-junit4", version.ref = "androidx-benchmark" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark-macro" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-compose" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profilerinstaller" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-room = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-sqlite = { module = "androidx.sqlite:sqlite-ktx", version.ref = "androidx-sqlite" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-espresso" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext-junit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-tracing-tracing = { module = "androidx.tracing:tracing", version.ref = "androidx-tracing" }
androidx-tracing-tracing-android = { module = "androidx.tracing:tracing-android", version.ref = "androidx-tracing" }
androidx-tracing-tracing-ktx = { module = "androidx.tracing:tracing-ktx", version.ref = "androidx-tracing" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "androidx-work" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-playservices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logback-android" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
opencds-cqf-fhir-cr = { module = "org.opencds.cqf.fhir:cqf-fhir-cr", version.ref = "opencds-cqf-fhir" }
opencds-cqf-fhir-jackson = { module = "org.opencds.cqf.fhir:cqf-fhir-jackson", version.ref = "opencds-cqf-fhir" }
opencds-cqf-fhir-utility = { module = "org.opencds.cqf.fhir:cqf-fhir-utility", version.ref = "opencds-cqf-fhir" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
fhir-ucum = { module = "org.fhir:ucum", version.ref = "fhir-ucum" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hapi-fhir-structures-r4 = { module = "ca.uhn.hapi.fhir:hapi-fhir-structures-r4", version.ref = "hapi-fhir" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
apache-commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "apache-commons-compress" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }
hapi-fhir-caching-guava = { module = "ca.uhn.hapi.fhir:hapi-fhir-caching-guava", version.ref = "hapi-fhir" }
hapi-fhir-core-convertors = { module = "ca.uhn.hapi.fhir:org.hl7.fhir.convertors", version.ref = "hapi-fhir-core" }
hapi-fhir-validation = { module = "ca.uhn.hapi.fhir:hapi-fhir-validation", version.ref = "hapi-fhir" }
hapi-fhir-validation-r4 = { module = "ca.uhn.hapi.fhir:hapi-fhir-validation-resources-r4", version.ref = "hapi-fhir" }
http = { module = "com.squareup.okhttp3:okhttp", version.ref = "http" }
http-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "http" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson-core" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-module-jaxb-annotations = { module = "com.fasterxml.jackson.module:jackson-module-jaxb-annotations", version.ref = "jackson" }
json-assert = { module = "org.skyscreamer:jsonassert", version.ref = "json-assert" }
json-tools-patch = { module = "com.github.java-json-tools:json-patch", version.ref = "json-tools-patch" }
mlkit-barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkit-barcode-scanning" }
mlkit-obj-detection = { module = "com.google.mlkit:object-detection", version.ref = "mlkit-object-detection" }
mlkit-obj-detection-custom = { module = "com.google.mlkit:object-detection-custom", version.ref = "mlkit-object-detection-custom" }
mock-web-server = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "http" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito-inline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
nimbus = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbus" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "sqlcipher" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
woodstox = { module = "com.fasterxml.woodstox:woodstox-core", version.ref = "woodstox" }
xerces = { module = "xerces:xercesImpl", version.ref = "xerces" }
xml-unit = { module = "org.xmlunit:xmlunit-core", version.ref = "xml-unit" }
zxing = { module = "com.google.zxing:core", version.ref = "zxing" }

[bundles]
androidx-tracing = ["androidx-tracing-tracing", "androidx-tracing-tracing-android", "androidx-tracing-tracing-ktx"]

[plugins]
android-application = { id = "com.android.application" }
android-library = { id = "com.android.library" }
android-test = { id = "com.android.test" }
androidx-benchmark = { id = "androidx.benchmark" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin" }
fladle = { id = "com.osacky.fladle" }
kotlin-android = { id = "org.jetbrains.kotlin.android" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization" }
ksp = { id = "com.google.devtools.ksp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ruler = { id = "com.spotify.ruler" }
spotless = { id = "com.diffplug.spotless" }
